// js/dom.js

export default  {
        calculadoraForm: document.getElementById('calculadora-form'),
        metodoCalculoSelect: document.getElementById('metodo-calculo'),
        ingresoDepartamentosGroup: document.getElementById('ingreso-departamentos-group'),
        ingresoTotalPersonasGroup: document.getElementById('ingreso-total-personas-group'),
        inputTotalPersonas: document.getElementById('input-total-personas'),
        deptoInputs: document.querySelectorAll('#depto-table input[type="number"]'),
        totalUnidadesCell: document.getElementById('total-unidades'),
        totalPersonasGeneralCell: document.getElementById('total-personas-general'),
        tipoSistemaSelect: document.getElementById('tipo-sistema'),
        acumulacionIngresadaInput: document.getElementById('acumulacion-ingresada'),
        potenciaIngresadaInput: document.getElementById('potencia-ingresada'),
        potenciaBcInput: document.getElementById('potencia-bc'),
        potenciaReInput: document.getElementById('potencia-re'),
        potenciaSalaCalderasRow: document.getElementById('potencia-sala-calderas-group'),
        potenciaBcRow: document.getElementById('potencia-bc-group'),
        potenciaReRow: document.getElementById('potencia-re-group'),
        potenciaTotalDisplayRow: document.getElementById('potencia-total-display-row'),
        potenciaTotalDisplaySpan: document.getElementById('potencia-total-display'),
        viewMode: document.getElementById('param-view-mode'),
        editMode: document.getElementById('param-edit-mode'),
        editBtn: document.getElementById('edit-params-btn'),
        saveBtn: document.getElementById('save-params-btn'),
        filasHoraPunta: document.querySelectorAll('.fila-hora-punta'),
        resultadoTable: document.getElementById('resultado-table'),
        resultadoTableBody: document.querySelector('#resultado-table tbody'),
        // TABS GRÁFICOS
        tabLine: document.getElementById('tab-line'),
        tabBar: document.getElementById('tab-bar'),
        tabMonthly: document.getElementById('tab-monthly'),
        tabEfficiency: document.getElementById('tab-efficiency'),
        // CONTAINERS GRÁFICOS
        lineChartContainer: document.getElementById('line-chart-container'),
        barChartContainer: document.getElementById('bar-chart-container'),
        monthlyChartContainer: document.getElementById('monthly-chart-container'),
        efficiencyChartContainer: document.getElementById('efficiency-chart-container'),
        lineChartCanvas: document.getElementById('lineChart').getContext('2d'),
        barChartCanvas: document.getElementById('barChart').getContext('2d'),
        monthlyChartCanvas: document.getElementById('monthlyChart').getContext('2d'),
        efficiencyChartCanvas: document.getElementById('efficiencyChart').getContext('2d'),
        // TABS ANÁLISIS
        tabEquipoSeleccionado: document.getElementById('tab-equipo-seleccionado'),
        tabSelection: document.getElementById('tab-selection'),
        tabPeakHours: document.getElementById('tab-peak-hours'),
        tabInstantFlow: document.getElementById('tab-instant-flow'),
        // CONTAINERS ANÁLISIS
        equipoSeleccionadoContainer: document.getElementById('equipo-seleccionado-container'),
        selectionTableContainer: document.getElementById('selection-table-container'),
        peakHoursContainer: document.getElementById('peak-hours-container'),
        instantFlowContainer: document.getElementById('instant-flow-container'),
        // ELEMENTOS NUEVA TABLA
        equipoSeleccionadoTableBody: document.querySelector('#equipo-seleccionado-table tbody'),
        equipoSelTempConsumo: document.getElementById('equipo-sel-temp-consumo'),
        equipoSelTempAcumulacion: document.getElementById('equipo-sel-temp-acumulacion'),
        equipoSelTempFria: document.getElementById('equipo-sel-temp-fria'),
        // ELEMENTOS TABLA SELECCIÓN
        selectionHeader: document.getElementById('selection-header'),
        selAnualM3: document.getElementById('sel-anual-m3'),
        selDiarioM3: document.getElementById('sel-diario-m3'),
        selRatio: document.getElementById('sel-ratio'),
        selCostoM3: document.getElementById('sel-costo-m3'),
        selCostoAnual: document.getElementById('sel-costo-anual'),
        // ELEMENTOS TABLA COMPARATIVA
        compScmAnualM3: document.getElementById('comp-scm-anual-m3'),
        compBcAnualM3: document.getElementById('comp-bc-anual-m3'),
        compTradAnualM3: document.getElementById('comp-trad-anual-m3'),
        compScmDiarioM3: document.getElementById('comp-scm-diario-m3'),
        compBcDiarioM3: document.getElementById('comp-bc-diario-m3'),
        compTradDiarioM3: document.getElementById('comp-trad-diario-m3'),
        compScmRatio: document.getElementById('comp-scm-ratio'),
        compBcRatio: document.getElementById('comp-bc-ratio'),
        compTradRatio: document.getElementById('comp-trad-ratio'),
        compScmCostoM3: document.getElementById('comp-scm-costo-m3'),
        compBcCostoM3: document.getElementById('comp-bc-costo-m3'),
        compTradCostoM3: document.getElementById('comp-trad-costo-m3'),
        compScmCostoAnual: document.getElementById('comp-scm-costo-anual'),
        compBcCostoAnual: document.getElementById('comp-bc-costo-anual'),
        compTradCostoAnual: document.getElementById('comp-trad-costo-anual'),
        // ELEMENTOS TABLA HORA PUNTA
        consumoPuntaCells: document.querySelectorAll('.consumo-punta-cell'),
        validadorPunta100: document.getElementById('validador-punta-100'),
        validadorPunta75: document.getElementById('validador-punta-75'),
        validadorPunta50: document.getElementById('validador-punta-50'),
        validadorPunta25: document.getElementById('validador-punta-25'),
        validadorPunta0: document.getElementById('validador-punta-0'),
        genPunta100: document.getElementById('gen-punta-100'),
        genPunta75: document.getElementById('gen-punta-75'),
        genPunta50: document.getElementById('gen-punta-50'),
        genPunta25: document.getElementById('gen-punta-25'),
        genPunta0: document.getElementById('gen-punta-0'),
        // ELEMENTOS CAUDALES
        produccionContinua50cSpan: document.getElementById('produccion-continua-50c'),
        produccionContinua60cSpan: document.getElementById('produccion-continua-60c'),
        produccionContinuaTempSpan: document.getElementById('prod-continua-temp'),
        produccionContinuaValorSpan: document.getElementById('produccion-continua-valor'),
        // DISCLAIMER
        disclaimerTempAcumulacion: document.getElementById('disclaimer-temp-acumulacion'),
        disclaimerTempFria: document.getElementById('disclaimer-temp-fria'),
    };